import {
    Poppins_100Thin as Thin,
    Poppins_100Thin_Italic as ThinItalic,
    Poppins_200ExtraLight as ExtraLight,
    Poppins_200ExtraLight_Italic as ExtraLightItalic,
    Poppins_300Light as Light,
    Poppins_300Light_Italic as LightItalic,
    Poppins_400Regular as Regular,
    Poppins_400Regular_Italic as RegularItalic,
    Poppins_500Medium as Medium,
    Poppins_500Medium_Italic as MediumItalic,
    Poppins_600SemiBold as SemiBold,
    Poppins_600SemiBold_Italic as SemiBoldItalic,
    Poppins_700Bold as Bold,
    Poppins_700Bold_Italic,
    Poppins_800ExtraBold,
    Poppins_800ExtraBold_Italic,
    Poppins_900Black,
    Poppins_900Black_Italic,
} from '@expo-google-fonts/poppins';

export default {
    Thin,
    ThinItalic,
    ExtraLight,
    ExtraLightItalic,
    Light,
    LightItalic,
    Regular,
    RegularItalic,
    Medium,
    MediumItalic,
    SemiBold,
    SemiBoldItalic,
    Bold,
    Poppins_700Bold_Italic,
    Poppins_800ExtraBold,
    Poppins_800ExtraBold_Italic,
    Poppins_900Black,
    Poppins_900Black_Italic,
}